### ISSUE TITLE
change the chance of the quality bonus for the farmer's delight cooking pot, based on the number of items present in the output

### ISSUE THREAD

**Issue by misterghast** [SiverDX/quality_food#17]
**The issue**
Right now, as far as I can tell looking at the mixin class, the accumulated quality in the pot is applied to the whole result stack at once in such a way that crafting the same recipe multiple times with high quality items in each individual craft can bias the result heavily towards a higher quality, even if you only used, say, a total of 3 silver items when making a stack of 40 outputs by repeatedly crafting.

**The solution?**
I think dividing the bonus quality chance by the number of outputs should work, if I'm assuming correctly how the system works. Then, for instance, 5 silver ingredients for 5 outputs has the highest chance of getting 5 silver outputs, instead of rolling an entire diamond stack every time because all the silver items biased the chance heavily. 

Forgive me if this has already been implemented and I just didn't notice it.

**Comment by SiverDX** [comment]
https://github.com/SiverDX/quality_food/blob/3013e38f7c43c4fc314a18a8d8b62e59617d9061/src/main/java/de/cadentem/quality_food/util/QualityUtils.java#L292-L301

at the moment lower rarities provide a lesser bonus and would need a higher quantity to skew the result

this is based on the furnace (single input) but basically with only silver quality items you'd not quite reach a point where you are very likely to get diamond results

maybe the problem here is more so the increased amount of input slots the cooking pot has
could divide the bonus by the amount of slots to reach the same result for the furnace (i.e. only silver doesn't give a guarantee of diamond rarity)
