### ISSUE TITLE
no_gui_cooking_pot from noguifd and copper_pot from miners_delight will not get food quality nbt tag

### ISSUE THREAD

**Issue by QLNPLUS** [SiverDX/quality_food#40]
when using 'miners_delight:copper_pot' and 'miners_delight:copper_pot' to cook food, quality will not set normally

**Comment by krjencik** [comment]
is my issue this one?: I cant use furnace.:
quality_food-1.21.1-2.2.1
Neoforge-21.1.79

[17lis2024 11:26:04.225] [Server thread/ERROR][net.minecraft.network.protocol.game.ServerPacketListener/]: Failed to handle packet net.minecraft.network.protocol.game.ServerboundUseItemOnPacket@418c850e, suppressing error

java.lang.NullPointerException: Cannot invoke "net.minecraft.resources.ResourceLocation.toString()" because "key" is null

[latest.log](https://github.com/user-attachments/files/17789841/latest.log)

**Comment by SiverDX** [comment]
> is my issue this one?: I cant use furnace.: quality_food-1.21.1-2.2.1 Neoforge-21.1.79
> 
> [17lis2024 11:26:04.225] [Server thread/ERROR][net.minecraft.network.protocol.game.ServerPacketListener/]: Failed to handle packet net.minecraft.network.protocol.game.ServerboundUseItemOnPacket@418c850e, suppressing error
> 
> java.lang.NullPointerException: Cannot invoke "net.minecraft.resources.ResourceLocation.toString()" because "key" is null
> 
> [latest.log](https://github.com/user-attachments/files/17789841/latest.log)

Wasn't able to replicate this
Notice that for you this issue occurred as well https://github.com/Octo-Studios/relics/issues/184

I changed some things - does that isse still occur with this version?
[quality_food-1.21.1-2.2.1.zip](https://github.com/user-attachments/files/17790471/quality_food-1.21.1-2.2.1.zip)

**Comment by krjencik** [comment]
ty a lot :) it seems to work now :)

**Comment by SiverDX** [comment]
Support for Miner's Delight has been added in the latest update (currently uploading)

**Comment by SiverDX** [comment]
No GUI FD seems restrictive in their access, meaning I can't import it as a dependency
(And I'm not going to bother adding manually downloading it and adding it as a local dependency)
(This is the same reason you can't download it from 3rd party launchers)

So I won't add support for that
